[package]
name = "clap3-0"
version = "2.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0"
trycmd = "0.15.0"


[[bin]]
name = "espanso"
path = "src/main.rs"
